apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: aksgitops.azurecr.io/azvote/azure-vote-front
    newTag: 7d739b40e030bbf67e84cc55ae51a73efa94e9af
  - name: aksgitops.azurecr.io/azvote/azure-vote-back
    newTag: 7d739b40e030bbf67e84cc55ae51a73efa94e9af
resources:
  - manifests.yaml