kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: stage
---
kind: Namespace
apiVersion: v1
metadata:
  name: production
---
kind: Namespace
apiVersion: v1
metadata:
  name: demo-agile-quebec
