apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: aksgitops.azurecr.io/azvote/azure-vote-front
    newTag: 15ef61de14c9192847feafe8f3958cb5298d9ef6
  - name: aksgitops.azurecr.io/azvote/azure-vote-back
    newTag: 15ef61de14c9192847feafe8f3958cb5298d9ef6
resources:
  - manifests.yaml