apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: aksgitops.azurecr.io/azvote/azure-vote-front
    newTag: d9bbec6239f5d88621f7d7ee95fdfe26ed697e6b
  - name: aksgitops.azurecr.io/azvote/azure-vote-back
    newTag: d9bbec6239f5d88621f7d7ee95fdfe26ed697e6b
resources:
  - manifests.yaml